#!/usr/bin/env python

import os
import os.path
import sys
import signal
import argparse

import ds3

class ArgumentError(Exception):
    def __init__(self, value):
        self.value = value
        
    def __str__(self):
        return repr(self.value)
    
class Arguments(object):
    def __init__(self):
        self.SERVICE_LIST = 'service_list'
        self.PUT_BUCKET = 'put_bucket'
        self.DELETE_BUCKET = 'delete_bucket'
        self.GET_BUCKET = 'get_bucket'
        self.PUT_OBJECT = 'put_object'
        self.DELETE_OBJECT = 'delete_object'
        self.GET_OBJECT = 'get_object'
        self.BULK_PUT = 'bulk_put'
        self.BULK_GET = 'bulk_get'
        
        parser = argparse.ArgumentParser(description='DS3 Command Line Interface')
        parser.add_argument('--command', dest='command', required=True, type=str, help='What command to perform', choices=[self.SERVICE_LIST, self.PUT_BUCKET, self.GET_BUCKET, self.DELETE_BUCKET, self.GET_OBJECT, self.PUT_OBJECT, self.DELETE_OBJECT, self.BULK_PUT, self.BULK_GET])
        parser.add_argument('--bucket', dest='bucket', type=str, help='The bucket name.  Required for any operations that target a bucket')
        parser.add_argument('--object', dest='objectkey', type=str, help='The filename or directory.  Required for any Object operations')
        parser.add_argument('--destination', dest='destination', type=str, help="Destination for Object. Required for Get Object")
        parser.add_argument('--endpoint', dest='endpoint', type=str, help='The DS3 endpoint.  Optionally you can set the environment variable "DS3_ENDPOINT"')
        parser.add_argument('--accessId', dest='accessId', type=str, help='The DS3 access id.  Optionally you can set the environment variable "DS3_ACCESS_KEY"')
        parser.add_argument('--key', dest='key', type=str, help='The DS3 secret key.  Optionally you can set the environment variable "DS3_SECRET_KEY"')
        args = parser.parse_args()
        
        self.accessId = os.getenv("DS3_ACCESS_KEY", args.accessId)
        self.key = os.getenv("DS3_SECRET_KEY", args.key)
        self.endpoint = os.getenv("DS3_ENDPOINT", args.endpoint)
        self.proxy = os.getenv("http_proxy", None)
  
        self.bucket = args.bucket
        self.objectkey = args.objectkey
        self.destination = args.destination
        self.command = args.command
        
        if not (self.accessId and self.key and self.endpoint):
            raise ArgumentError('accessId, key, and endpoint must all be set')
  
        if (args.command in [self.PUT_BUCKET, self.DELETE_BUCKET, self.GET_BUCKET]) and not args.bucket:
            raise ArgumentError('must specify bucket for bucket operations')
        
        elif (args.command in [self.PUT_OBJECT, self.DELETE_OBJECT, self.BULK_PUT]) and (not args.objectkey or not args.bucket):
            raise ArgumentError('must specify bucket and object for Put and Delete object operations') 
        
        elif (args.command in [self.GET_OBJECT, self.BULK_GET]) and (not args.objectkey or not args.bucket or not args.destination):
            raise ArgumentError('must specify bucket, object, and destination for Get Object operations') 


def signal_handler(signal, frame):
    print "Detected Ctrl-C, closing program."
    sys.exit(0)

def ensure_dir_exists(dir_name):
    if not os.path.exists(dir_name):
        os.makedirs(dir_name)

def place_file(file_name, file_data):
    dir_name = os.path.dirname(file_name)
    if dir_name != '':
        ensure_dir_exists(dir_name)
    output_file = open(file_name, 'w')
    output_file.write(file_data)
    output_file.close()


def create_object_list(directory):
    files = []
    for entry in os.listdir(directory):
        full_path = os.path.join(directory, entry)
        if os.path.isdir(full_path):
            files.append(create_object_list(full_path))
        elif os.path.isfile(full_path):
            files.append(ds3.Object(full_path, os.path.getsize(full_path)))
        else:
            print "Unkown type"
    return files

def print_service_list_result(result):
    print "Service List (Buckets) Result for owner: ", result.owner.ownerid, "(", result.owner.displayname, ")"
    print " "
    
    for bucket in result.get_buckets():
        print "    ", bucket.name, "    ", bucket.creationdate
        
    print ""
    
def print_get_bucket_result(result):
    print "Get Bucket result for", result.name, result.creationdate
    print "Prefix=", result.prefix, "Marker=", result.marker, "MaxKeys=", result.maxkeys
    print "Contents:"
    for c in result.get_contents():
        print "Key=", c.key, "LastModified=", c.lastmodified, "ETag=", c.etag, "Size=", c.size, "StorgeClass=", c.storageclass
  
    
def bulk_put(client, bucket, result):
    print "BULK JOB ID", result.jobid
    for putobj in result.objectlist: 
        try:
            response = client.put_object(ds3.PutObjectRequest(bucket, putobj.name))
            print "Put", putobj.name, "DONE"
        except ds3.RequestFailed as e:
            print "Put", putobj.name, "FAILED"
    
def bulk_get(client, bucket, destinationdir, result):
    #print "BULK GET JOB ID",
    for getobj in result.objectlist:
        print "GET", getobj.name
    
def main():
    signal.signal(signal.SIGINT, signal_handler)
    args = Arguments()
    
    credentials = ds3.Credentials(args.accessId, args.key)
    if credentials.isValid == False:
        print 'Error: Credentials not valid'
        sys.exit(1)
        
    client = ds3.Client(args.endpoint, credentials)
    
    cmd = args.command
    try:
        if cmd == args.SERVICE_LIST:
            response = client.get_service(ds3.GetServiceRequest())
            print_service_list_result(response.result)
        elif cmd == args.PUT_BUCKET:
            response = client.put_bucket(ds3.PutBucketRequest(args.bucket))
        elif cmd == args.DELETE_BUCKET:
            response = client.delete_bucket(ds3.DeleteBucketRequest(args.bucket))
        elif cmd == args.GET_BUCKET:
            response = client.get_bucket(ds3.GetBucketRequest(args.bucket))
            print_get_bucket_result(response.result)
        elif cmd == args.PUT_OBJECT:
            response = client.put_object(ds3.PutObjectRequest(args.bucket, args.objectkey))
        elif cmd == args.DELETE_OBJECT:
            response = client.delete_object(ds3.DeleteObjectRequest(args.bucket, args.objectkey))
        elif cmd == args.GET_OBJECT:
            response = client.get_object(ds3.GetObjectRequest(args.bucket, args.objectkey, args.destination))
        elif cmd == args.BULK_PUT:
            files = create_object_list(args.objectkey)
            response = client.bulk_put(ds3.BulkPutRequest(args.bucket, files))
            bulk_put(client, args.bucket, response.result)
        elif cmd == args.BULK_GET:
            files = create_object_list(args.objectkey)
            response = client.bulk_get(ds3.BulkGetRequest(args.bucket, files))
            bulk_get(client, args.bucket, args.destination, response.result)
        else:
            print "Request", cmd, "is not handled"
            sys.exit(1)
            
    except ds3.RequestFailed as e:
        print "\nRequest", cmd, "failed", e
        print "\nCode: ", e.code
        print "HttpErrorCode: ", e.httperrorcode
        print "Message: ", e.message
    except ds3.RequestNotImplemented:
        print "Request", cmd, "is not implemented in the SDK"
    else:
        print "\nRequest", cmd, "successfully completed..."
        response.close()
        
    sys.exit(0)

if __name__ == '__main__':
    main()
