#!/usr/bin/env python

import os
import os.path
import sys
import signal
import argparse

import ds3

class ArgumentError(Exception):
    def __init__(self, value):
        self.value = value
        
    def __str__(self):
        return repr(self.value)
    
class Arguments(object):
    def __init__(self):
        self.SERVICE_LIST = 'service_list'
        self.PUT_BUCKET = 'put_bucket'
        self.DELETE_BUCKET = 'delete_bucket'
        self.GET_BUCKET = 'get_bucket'
        self.PUT_OBJECT = 'put_object'
        self.DELETE_OBJECT = 'delete_object'
        self.GET_OBJECT = 'get_object'
        self.BULK_PUT = 'bulk_put'
        self.BULK_GET = 'bulk_get'
        self.GET_JOBS = 'get_jobs'
        self.GET_JOB = 'get_job'
        self.DELETE_JOB = 'delete_job'
        
        parser = argparse.ArgumentParser(description='DS3 Command Line Interface')
        parser.add_argument('--command', dest='command', required=True, type=str, help='What command to perform', choices=[self.SERVICE_LIST, self.PUT_BUCKET,self.GET_BUCKET, self.DELETE_BUCKET, self.GET_OBJECT, self.PUT_OBJECT, self.DELETE_OBJECT, self.BULK_PUT, self.BULK_GET, self.GET_JOBS, self.GET_JOB, self.DELETE_JOB])
        parser.add_argument('--bucket', dest='bucket', type=str, help='The bucket name.  Required for any operations that target a bucket')
        parser.add_argument('--object', dest='objectkey', type=str, help='The Object filename.  Required for any Object operations')
        parser.add_argument('--directory', dest='directory', type=str, help="Directory for Bulk and Get commands.")
        parser.add_argument('--destination', dest='destination', type=str, help="Destination directory for for Bulk get command.")
        parser.add_argument('--endpoint', dest='endpoint', type=str, help='The DS3 endpoint.  Optionally you can set the environment variable "DS3_ENDPOINT"')
        parser.add_argument('--accessId', dest='accessId', type=str, help='The DS3 access id.  Optionally you can set the environment variable "DS3_ACCESS_KEY"')
        parser.add_argument('--key', dest='key', type=str, help='The DS3 secret key.  Optionally you can set the environment variable "DS3_SECRET_KEY"')
        parser.add_argument('--jobid', dest='jobid', type=str, help='Job (Prime) ID.  Required for any Job Prime Operations')
        parser.add_argument('--prefix', dest='prefix', type=str, help='Prefix for Get Bucket.')
        parser.add_argument('--maxkeys', dest='maxkeys', type=str, help='Max-Keys for Get Bucket.')
        parser.add_argument('--marker', dest='marker', type=str, help='Starting Marker for Get Bucket.')

        args = parser.parse_args()
        
        self.accessId = os.getenv("DS3_ACCESS_KEY", args.accessId)
        self.key = os.getenv("DS3_SECRET_KEY", args.key)
        self.endpoint = os.getenv("DS3_ENDPOINT", args.endpoint)
        self.proxy = os.getenv("http_proxy", None)
  
        self.bucket = args.bucket
        self.objectkey = args.objectkey
        self.directory = args.directory
        self.destination = args.destination
        self.jobid = args.jobid
        self.command = args.command
        self.prefix = args.prefix
        self.maxkeys = args.maxkeys
        self.marker = args.marker
        self.prefix = args.prefix
        
        if not (self.accessId and self.key and self.endpoint):
            raise ArgumentError('accessId, key, and endpoint must all be set')
  
        if (args.command in [self.PUT_BUCKET, self.DELETE_BUCKET, self.GET_BUCKET]) and not args.bucket:
            raise ArgumentError('must specify bucket for bucket operations')
        
        elif (args.command in [self.PUT_OBJECT, self.DELETE_OBJECT]) and (not args.objectkey or not args.bucket):
            raise ArgumentError('must specify bucket and object for Put and Delete object operations') 
        
        elif (args.command in [self.BULK_PUT]) and (not args.directory or not args.bucket):
            raise ArgumentError('must specify bucket and source directory for Bulk PUT operations') 
        
        elif (args.command in [self.BULK_GET]) and (not args.directory or not args.bucket or not args.destination):
            raise ArgumentError('must specify bucket, source and destination directories for Bulk GET operations') 
        
        elif (args.command in [self.GET_OBJECT]) and (not args.objectkey or not args.bucket or not args.destination):
            raise ArgumentError('must specify bucket, object, and destination for Get Object operations')
        
        elif (args.command in [self.GET_JOBS] and not args.bucket):
             raise ArgumentError('must specify bucket in Get Jobs operation')
         
        elif (args.command in [self.GET_JOB, self.DELETE_JOB] and not args.jobid):
             raise ArgumentError('must specify Prime ID in Get and Delete Job operation')       


def signal_handler(signal, frame):
    print "Detected Ctrl-C, closing program."
    sys.exit(0)

def ensure_dir_exists(dir_name):
    if not os.path.exists(dir_name):
        os.makedirs(dir_name)

def place_file(file_name, file_data):
    dir_name = os.path.dirname(file_name)
    if dir_name != '':
        ensure_dir_exists(dir_name)
    output_file = open(file_name, 'w')
    output_file.write(file_data)
    output_file.close()


def create_object_list(directory):
    files = []
    for entry in os.listdir(directory):
        full_path = os.path.join(directory, entry)
        if os.path.isdir(full_path):
            files.append(create_object_list(full_path))
        elif os.path.isfile(full_path):
            files.append(ds3.Object(full_path.replace("\\", "/"), os.path.getsize(full_path)))
        else:
            print "Unkown type"
    return files

def print_service_list_result(result):
    print "Service List (Buckets) Result for owner: ", result.owner.ownerid, "(", result.owner.displayname, ")"
    print " "
    
    for bucket in result.get_buckets():
        print "    ", bucket.name, "    ", bucket.creationdate
        
    print ""
    
def print_get_bucket_result(result):
    print "Get Bucket result for", result.name, result.creationdate
    print "Prefix=", result.prefix, "Marker=", result.marker, "MaxKeys=", result.maxkeys
    print "Contents:"
    for c in result.get_contents():
        print "Key=", c.key, "LastModified=", c.lastmodified, "ETag=", c.etag, "Size=", c.size, "StorgeClass=", c.storageclass
  
    
def bulk_put(client, bucket, result):
    print "BULK JOB ID", result.jobid
    for putobj in result.objectlist: 
        try:
            response = client.put_object(ds3.PutObjectRequest(bucket, putobj.name.replace("\\", "/")))
            print "Put", putobj.name, "DONE"
        except ds3.RequestFailed as e:
            print "Put", putobj.name, "FAILED"
    
def bulk_get(client, bucket, destinationdir, result):
    print "BULK GET JOB ID", result.jobid
    for bulkobj in result.objectlist:
        try:
            response = client.get_object(ds3.GetObjectRequest(bucket, bulkobj.name, destinationdir ))
            print "Get", bulkobj.name, "DONE"
        except ds3.RequestFailed as e:
            print "Get", bulkobj.name, "FAILED"      
        
def print_jobs(result, bucket):
    print "Prime Jobs for bucket", bucket
    for prime in result.primes:
        print "Created at", prime.createdat, "Active", prime.active, "Id", prime.id, "Type", prime.requesttype  
        
    
def main():
    signal.signal(signal.SIGINT, signal_handler)
    args = Arguments()
    
    credentials = ds3.Credentials(args.accessId, args.key)
    if credentials.is_valid == False:
        print 'Error: Credentials not valid'
        sys.exit(1)
        
    client = ds3.Client(args.endpoint, credentials)
    
    cmd = args.command
    try:
        if cmd == args.SERVICE_LIST:
            response = client.get_service(ds3.GetServiceRequest())
            print_service_list_result(response.result)
        elif cmd == args.PUT_BUCKET:
            response = client.put_bucket(ds3.PutBucketRequest(args.bucket))
        elif cmd == args.DELETE_BUCKET:
            response = client.delete_bucket(ds3.DeleteBucketRequest(args.bucket))
        elif cmd == args.GET_BUCKET:
            request = ds3.GetBucketRequest(args.bucket)
            if args.prefix:
                request.with_prefix(args.prefix)
            if args.marker:
                request.with_marker(args.marker)
            if args.maxkeys:
                request.with_maxkeys(args.maxkeys)
    
            response = client.get_bucket(request)
            print_get_bucket_result(response.result)
        elif cmd == args.PUT_OBJECT:
            response = client.put_object(ds3.PutObjectRequest(args.bucket, args.objectkey))
        elif cmd == args.DELETE_OBJECT:
            response = client.delete_object(ds3.DeleteObjectRequest(args.bucket, args.objectkey))
        elif cmd == args.GET_OBJECT:
            response = client.get_object(ds3.GetObjectRequest(args.bucket, args.objectkey, args.directory))
        elif cmd == args.BULK_PUT:
            files = create_object_list(args.directory)
            response = client.bulk_put(ds3.BulkPutRequest(args.bucket, files))
            bulk_put(ds3.Client(args.endpoint, credentials), args.bucket, response.result)
        elif cmd == args.BULK_GET:
            files = create_object_list(args.directory)
            response = client.bulk_get(ds3.BulkGetRequest(args.bucket, files))
            bulk_get(client, args.bucket, args.destination, response.result)
        elif cmd == args.GET_JOBS:
            response = client.get_jobs(ds3.GetJobsRequest(args.bucket))
            print_jobs(response.result, args.bucket)
        elif cmd == args.GET_JOB:
            response = client.get_job(ds3.GetJobRequest(args.jobid))
        elif cmd == args.DELETE_JOB:
            response = client.delete_job(ds3.DeleteJobRequest(args.jobid))
        else:
            print "Request", cmd, "is not handled"
            sys.exit(1)
            
    except ds3.RequestFailed as e:
        print "\nRequest", cmd, "failed", e
        print "\nCode: ", e.code
        print "HttpErrorCode: ", e.httperrorcode
        print "Message: ", e.message
    except NotImplementedError:
        print "Request", cmd, "is not implemented in the SDK"
    else:
        print "\nRequest", cmd, "successfully completed..."
        response.close()
        
    sys.exit(0)

if __name__ == '__main__':
    main()
